### ISSUE TITLE
Infoview should indicate when server is not started

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#114] opened 2022-02-04 12:55 UTC
Right now it shows "no info found" even if the server did not start.

**Comment by lovettchris** [comment] 2022-02-11 20:21
Really? Mine says "Waiting for Lean server to start..."  was this fixed recently perhaps?

**Comment by gebner** [comment] 2022-03-17 08:44
I think I hit that issue back when we didn't start a Lean server for some directories that didn't contain lakefiles.  I still see a similar issue when the server is terminated manually: #155

**Comment by Vtec234** [comment] 2022-05-16 21:56
It seems like another instance of this issue occurs when there are errors in `lakefile.lean`. In this case `lake serve` enters a mode in which `lakefile.lean` can be edited, but every other file should immediately fail (see leanprover/lake#52). However the infoview gets stuck displaying "Waiting for server to start...", even when `lakefile.lean` is the active editor. See also [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/VSCode.20.22Waiting.20for.20lean.20server.20to.20start.2E.2E.2E.22).

**Comment by lovettchris** [comment] 2022-05-16 23:43
Specifically: "part of the problem seems to be that when lakefile.lean contains errors, lake serve prints them e.g. like so

```
./lakefile.lean:5:18: error: unknown constant 'Lake.PackageFacet.olean'
error: package configuration `./lakefile.lean` has errors
```
but then continues to execute the LSP server anyway. From the vscode extension's perspective, since it received no error code the server started up okay, and then this somehow leads to showing "Waiting" forever. Perhaps Lake should just exit with 1 at this point. /CC @Mac

Mac: @Wojciech Nawrocki this is actually a new feature, not a bug. See Lake [#52](https://github.com/leanprover/lake/pull/52). :stuck_out_tongue_wink:

Wojciech Nawrocki: I see! Then vscode-lean4 should detect and handle this case.

**Comment by marianaalanis93** [comment] 2022-06-28 17:34
Fixed and merged on https://github.com/leanprover/vscode-lean4/pull/159

**Closed by marianaalanis93** 2022-06-28 17:34 UTC
