### ISSUE TITLE
Welcome page doesn't open

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/vscode-lean4#529] opened 2024-10-01 11:47 UTC
### Description

If I (uninstall and re)install the extension, the welcome page does not open automatically (in contrast to what the README says). I am on Windows.

However, the ∀-symbol is always visible, so no need to create an empty file anymore before clicking it. (Related Lean PR: https://github.com/leanprover/lean4/pull/5559 )

**Comment by mhuisi** [comment] 2024-10-01 15:23
It's worth pointing out that VS Code may not open the welcome page again if you uninstall and re-install the extension. I believe it only does that on first install.

I've also seen this fail a few times on the first install for unknown reasons, but this is almost surely on VS Code's side. So it does work sometimes, and in case it doesn't, we provide instructions.

Having looked into this for a couple of hours before, I'm not sure what to do about this other than move away from VS Code's welcome page mechanism entirely and use a custom HTML page and custom state management to detect the first installation of the extension instead.

**Comment by mhuisi** [comment] 2024-10-01 18:16
> Ok, I tried to avoid caching issues by uninstalling, closing VSCode, reopening VSCode and then installing

To my knowledge, the cache is permanent (or at least it definitely persists past closing VS Code).

> If you've already tried this hard before

I think it's fine to keep it open. There's a work item somewhere in my backlog to replace the welcome page with a custom mechanism, and we can close this issue when that eventually happens.

**Comment by mhuisi** [comment] 2024-11-20 19:18
I reported an issue related to the welcome page in the VS Code repo (microsoft/vscode#232425) and since 1.95.*, I can't reproduce issues related to the setup guide on either Windows or Linux anymore, provided that the extension is being installed for the first time (i.e. all VS Code config folders have been wiped before that). Let's hope that it is fixed now. Please feel free to create another issue if this comes up again on a fresh setup with VS Code 1.95.* or later for you or one of your students.

**Closed by mhuisi** 2024-11-20 19:18 UTC
Labels: bug
