### ISSUE TITLE
Intelligent Line wrapping for some theorems 

### ISSUE THREAD

**Issue by marianaalanis93** [leanprover/vscode-lean4#132] opened 2022-02-17 21:56 UTC
Check mathlib documentation and code in order to check inteligent line wrapping for some theorems involving multiple nested parentheses.

https://leanprover-community.github.io/mathlib_docs/measure_theory/covering/besicovitch_vector_space.html#besicovitch.exists_good_%CE%B4

This issue is related to: https://github.com/leanprover/vscode-lean4/issues/107

**Comment by marianaalanis93** [comment] 2022-02-21 21:26
Related PR #133

**Comment by sarahsmith31** [comment] 2022-07-06 17:29
Related PR is no longer applicable, Sebastian and [Vtec234](https://github.com/Vtec234) may have an appropriate solution on Zulip? But this may be low priority for now

**Comment by gebner** [comment] 2022-07-06 18:00
Implementing this feature is probably a bigger refactoring.  As far as I see it, there are two possible approaches:
1. Send the column width with every RPC call that returns a `CodeWithInfos` (directly or indirectly).  This means we'd need to re-request goals etc. when the infoview is resized, which is decidedly suboptimal.
2. Extend the `CodeWithInfos` type so that it contains formatting information (i.e., `group`, `fill`, `nest`, etc.).  This requires reimplementing the/a formatter in the vscode/neovim/... extensions.

**Comment by Kha** [comment] 2022-07-06 20:20
> 1. This means we'd need to re-request goals etc. when the infoview is resized, which is decidedly suboptimal.

That's true, but on the other hand... how often does that happen?

Ideally the refresh would happen only when releasing the mouse button.

**Comment by gebner** [comment] 2022-07-06 20:46
> how often does that happen? Ideally the refresh would happen only when releasing the mouse button.

For example when resizing the window.  And we don't know if the mouse button is pressed while resizing.  (But it's always possible to add a delay.)

Another issue is that this kills all popups.  Re-requesting might also not be possible for paused infos.

**Comment by gebner** [comment] 2022-07-07 07:54
Duplicate of #107.

**Closed by gebner** 2022-07-07 07:54 UTC
Labels: low priority
