### ISSUE TITLE
Search for declarations in open files (ctrl+t)

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#46] opened 2021-10-08 21:29 UTC
lean4 server needs to add this.

**Comment by leodemoura** [comment] 2021-12-10 16:44
@lovettchris Could you please describe the required changes on the Lean LSP server?

**Comment by Kha** [comment] 2021-12-10 17:26
By building on top of @Garmelon's work when that is ready, it should be straightforward to support this even for closed files - with the same approximation properties, most likely "state from the last successful full build".

**Comment by Kha** [comment] 2022-01-11 13:27
Duplicate of leanprover/lean4#396

**Closed by Kha** 2022-01-11 13:27 UTC
